# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drawSetup = QtWidgets.QPushButton(self.centralwidget)
        self.drawSetup.setGeometry(QtCore.QRect(300, 120, 201, 27))
        self.drawSetup.setObjectName("drawSetup")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(680, 520, 96, 27))
        self.exitButton.setObjectName("exitButton")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(30, 50, 641, 26))
        self.url.setObjectName("url")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setGeometry(QtCore.QRect(30, 20, 751, 20))
        self.urlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urlLabel.setObjectName("urlLabel")
        self.colorSetup = QtWidgets.QPushButton(self.centralwidget)
        self.colorSetup.setGeometry(QtCore.QRect(280, 220, 241, 27))
        self.colorSetup.setObjectName("colorSetup")
        self.urlLoad = QtWidgets.QPushButton(self.centralwidget)
        self.urlLoad.setGeometry(QtCore.QRect(690, 50, 96, 27))
        self.urlLoad.setObjectName("urlLoad")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(33, 80, 751, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.generalStatus = QtWidgets.QLabel(self.centralwidget)
        self.generalStatus.setGeometry(QtCore.QRect(30, 460, 741, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.generalStatus.setPalette(palette)
        self.generalStatus.setText("")
        self.generalStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.generalStatus.setObjectName("generalStatus")
        self.drawButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawButton.setGeometry(QtCore.QRect(230, 490, 351, 61))
        self.drawButton.setObjectName("drawButton")
        self.drawStatus = QtWidgets.QLabel(self.centralwidget)
        self.drawStatus.setGeometry(QtCore.QRect(30, 160, 751, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.drawStatus.setPalette(palette)
        self.drawStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.drawStatus.setObjectName("drawStatus")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 340, 751, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.colorAreaStatus = QtWidgets.QLabel(self.centralwidget)
        self.colorAreaStatus.setGeometry(QtCore.QRect(33, 260, 751, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.colorAreaStatus.setPalette(palette)
        self.colorAreaStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.colorAreaStatus.setObjectName("colorAreaStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.drawSetup.setText(_translate("MainWindow", "Définir la zone de dessin"))
        self.exitButton.setText(_translate("MainWindow", "Quitter"))
        self.urlLabel.setText(_translate("MainWindow", "Url de l\'image"))
        self.colorSetup.setText(_translate("MainWindow", "Définir la zone des couleurs"))
        self.urlLoad.setText(_translate("MainWindow", "Charger"))
        self.statusLabel.setText(_translate("MainWindow", "Aucune image chargée"))
        self.drawButton.setText(_translate("MainWindow", "Dessiner"))
        self.drawStatus.setText(_translate("MainWindow", "Zone de dessin non configurée"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.colorAreaStatus.setText(_translate("MainWindow", "Zone des couleurs non configurée"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

